name: JoinProtection
version: '${version}'
main: me.rockquiet.joinprotection.JoinProtection
description: Protects players from mobs and damage for a set period of time after they join
author: rockquiet
folia-supported: true
# using 1.13 for the version check to work properly
api-version: 1.13

softdepend:
  - PlaceholderAPI
  - MiniPlaceholders
  - LuckPerms

commands:
  joinprotection:
    description: joinprotection command

permissions:
  joinprotection.use:
    description: if the player has join protection
    default: true
  joinprotection.use-world:
    description: if the player has world protection
    default: true
  joinprotection.reload:
    description: reloads the config
    default: op
  joinprotection.bypass.cancel-on-move:
    description: bypasses the cancel on move option
    default: false
  joinprotection.bypass.cancel-on-attack:
    description: bypasses the cancel on attack option
    default: false
  joinprotection.bypass.cancel-on-block-interact:
    description: bypasses the cancel on block interact option
    default: false
  joinprotection.bypass.world-list:
    description: bypasses the world-list
    default: false
  joinprotection.bypass.*:
    description: grants all bypass permissions
    default: false
    children:
      joinprotection.bypass.cancel-on-move: true
      joinprotection.bypass.cancel-on-attack: true
      joinprotection.bypass.cancel-on-block-interact: true
      joinprotection.bypass.world-list: true
  joinprotection.*:
    description: grants all permissions of the plugin
    default: false
    children:
      joinprotection.use: true
      joinprotection.use-world: true
      joinprotection.reload: true
      joinprotection.bypass.*: true
